"""Markdown report drafts from recon index (Tier A)."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .scoring import NOTABLE_THRESHOLD, is_notable, sort_key
from .store import OUTPUT_DIR


def build_report_md(
    target: str,
    findings: list[dict[str, Any]],
    *,
    notable_only: bool = True,
    threshold: int = NOTABLE_THRESHOLD,
    max_rows: int = 80,
) -> str:
    rows = [f for f in findings if f.get("target") == target]
    if notable_only:
        rows = [f for f in rows if is_notable(f, threshold)]
    rows = sorted(rows, key=sort_key)[:max_rows]

    by_sev: dict[str, int] = {}
    by_mod: dict[str, int] = {}
    for f in rows:
        by_sev[f.get("severity", "?")] = by_sev.get(f.get("severity", "?"), 0) + 1
        by_mod[f.get("module", "?")] = by_mod.get(f.get("module", "?"), 0) + 1

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        f"# Recon report draft — `{target}`",
        "",
        f"_Generated by reconkit {now}. Detection-only candidates — verify manually under your RoE._",
        "",
        "## Summary",
        "",
        f"- Records in this draft: **{len(rows)}**"
        + (" (notable only)" if notable_only else " (all)"),
        f"- Severity mix: {by_sev or '{}'}",
        f"- Modules: {by_mod or '{}'}",
        f"- Output dir: `{OUTPUT_DIR / target.replace('*', '_')}`",
        "",
        "## Notable / prioritized items",
        "",
    ]
    if not rows:
        lines.append("_No notable records. Run recon + `/findings reindex`, or lower the threshold._")
        lines.append("")
    else:
        lines += [
            "| Score | Sev | Module | Type | Title | Asset |",
            "|------:|-----|--------|------|-------|-------|",
        ]
        for f in rows:
            asset = (f.get("asset") or "").replace("|", "\\|")[:80]
            title = (f.get("title") or "").replace("|", "\\|")[:40]
            lines.append(
                f"| {f.get('score', '')} | {f.get('severity', '')} | {f.get('module', '')} | "
                f"{f.get('ftype', '')} | {title} | `{asset}` |"
            )
        lines.append("")
        lines.append("## Evidence notes")
        lines.append("")
        for i, f in enumerate(rows[:25], 1):
            lines.append(f"### {i}. {f.get('title')} — score {f.get('score')}")
            lines.append("")
            lines.append(f"- **Asset:** `{f.get('asset', '')}`")
            lines.append(f"- **Source:** `{f.get('source_file', '')}`")
            lines.append(f"- **Tags:** {', '.join(f.get('tags') or [])}")
            ev = (f.get("evidence") or "")[:500]
            lines.append(f"- **Evidence:**")
            lines.append("```")
            lines.append(ev)
            lines.append("```")
            lines.append("")

    # Attach saved proofs from prove layer if any
    try:
        from prove.store import load_proofs

        proofs = load_proofs(target)
    except Exception:
        proofs = []
    if proofs:
        lines += [
            "## Safe validation proofs (v2.1 prove layer)",
            "",
            "_Non-destructive rechecks only — not full exploitation._",
            "",
            "| Status | Technique | Title | Asset |",
            "|--------|-----------|-------|-------|",
        ]
        for p in proofs[:40]:
            asset = (p.get("asset") or "").replace("|", "\\|")[:60]
            title = (p.get("title") or "").replace("|", "\\|")[:40]
            lines.append(
                f"| {p.get('status')} | {p.get('technique')} | {title} | `{asset}` |"
            )
        lines.append("")
        confirmed = [p for p in proofs if p.get("status") == "confirmed"]
        if confirmed:
            lines.append("### Confirmed proof notes")
            lines.append("")
            for i, p in enumerate(confirmed[:15], 1):
                lines.append(f"#### {i}. {p.get('title')} (`{p.get('id')}`)")
                lines.append("")
                lines.append(f"- **Technique:** {p.get('technique')}")
                lines.append(f"- **Impact:** {p.get('impact_note') or '(see evidence)'}")
                lines.append("```")
                lines.append((p.get("evidence") or "")[:600])
                lines.append("```")
                lines.append("")

    lines += [
        "## Next steps (manual)",
        "",
        "1. Confirm each item is in scope and within program rules.",
        "2. Reproduce high/critical with your own methodology (or run `/prove`).",
        "3. Do not treat automated detection as full exploitability without proof.",
        "",
    ]
    return "\n".join(lines)


def write_report(
    target: str,
    findings: list[dict[str, Any]],
    *,
    notable_only: bool = True,
    out_path: Path | None = None,
) -> Path:
    md = build_report_md(target, findings, notable_only=notable_only)
    outdir = OUTPUT_DIR / target.replace("*", "_")
    outdir.mkdir(parents=True, exist_ok=True)
    path = out_path or (outdir / "report_draft.md")
    path.write_text(md, encoding="utf-8")
    return path
